# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginScreen(object):
    def setupUi(self, LoginScreen):
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.resize(730, 122)
        font = QtGui.QFont()
        font.setPointSize(12)
        LoginScreen.setFont(font)
        self.centralwidget = QtWidgets.QWidget(LoginScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 704, 89))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.horizontalLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.txt_ip = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.txt_ip.setObjectName("txt_ip")
        self.gridLayout.addWidget(self.txt_ip, 1, 5, 1, 1)
        self.txt_email = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.txt_email.setObjectName("txt_email")
        self.gridLayout.addWidget(self.txt_email, 1, 1, 1, 1)
        self.txt_pass = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.txt_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_pass.setObjectName("txt_pass")
        self.gridLayout.addWidget(self.txt_pass, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.btn_Login = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_Login.setObjectName("btn_Login")
        self.gridLayout.addWidget(self.btn_Login, 0, 6, 1, 1)
        self.cb_rememberMe = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.cb_rememberMe.setObjectName("cb_rememberMe")
        self.gridLayout.addWidget(self.cb_rememberMe, 1, 6, 1, 1)
        LoginScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "MainWindow"))
        self.label_3.setText(_translate("LoginScreen", "IP Adresi"))
        self.label.setText(_translate("LoginScreen", "E Posta"))
        self.txt_ip.setPlaceholderText(_translate("LoginScreen", "192.168.X.X"))
        self.txt_email.setPlaceholderText(_translate("LoginScreen", "xxxx@xxx.xxx"))
        self.txt_pass.setPlaceholderText(_translate("LoginScreen", "xxxxxxxxxxxxx"))
        self.label_2.setText(_translate("LoginScreen", "Şifre"))
        self.btn_Login.setText(_translate("LoginScreen", "Giriş Yap"))
        self.cb_rememberMe.setText(_translate("LoginScreen", "Beni Hatırla"))
